### ISSUE TITLE
Not working under Debian?

### ISSUE THREAD

**Issue by ghost** [luki1412/Invert#1]
Was looking for a light skin for steam here under Debian bullseye and bookworm.

Created a skin folder ~/.steam/debian-installation/skins and placed your folder 'Invert_V3.57' there.

Have those 2 skins there

![Bildschirmfoto_2023-03-20_15-40-47](https://user-images.githubusercontent.com/17964433/226374492-7a0dbb6e-7874-4ad6-8041-8585408d9753.png)

but I am a bit suprized, as only one skin is visible in steam ...

![Bildschirmfoto_2023-03-20_15-43-53](https://user-images.githubusercontent.com/17964433/226375461-bc6098db-70ed-4bbb-a7b2-def95a7c307a.png)

br KH

**Comment by ghost** [comment]
My fault. Not Invert_V3.57, but the Invert folder has to be placed there.

Sorry, br  KH

**Comment by luki1412** [comment]
> My fault. Not Invert_V3.57, but the Invert folder has to be placed there.
> 
> Sorry, br KH

Correct. Invert_V3.57.zip is the name of the zip file so you probably extracted it into a folder called Invert_V3.57 and moved it to skins but Invert_V3.57 contains the Invert folder and a readme file. That Invert folder is supposed to go into the skins folder.
